### ISSUE TITLE
Passwords with special characters are problematic

### ISSUE THREAD

**Issue by LawrenceJGD** [lignux-social/nonamebox-account#1]
I was trying to log in to the **webmail** and **Nextcloud** but I couldn't. I
use a password generator that I set up to include special characters like
`' " * _ - "` and others, I tried to change the password and I generated another
one with the same configuration but the problem was still happening, last I
tried to use a password without special characters and then I was able to log
in to both services.

These were the two keys that I used and that gave me problems:

```
"rM$Xg~ptz*9dtD4vJ-\
2M'J-n>APk9+"~N%:J2{
```

And this is a password similar to the one that it worked for me: 

```
GVNfEB7ApUs3C8DAyPnq
```

---

Estuve intentando acceder al **webmail** y a **Nextcloud** pero no podía. Uso un
generador de contraseña que configuré para que incluyera caracteres como
`' " * _ - "` y otros más, probé a cambiar la contraseña y generé una con la
misma configuración pero seguía sucediendo, por ultimo probé una contraseña
sin caracteres especiales y entonces sí funciono.

Estas fueron las dos claves que usé y que dieron problemas:

```
"rM$Xg~ptz*9dtD4vJ-\
2M'J-n>APk9+"~N%:J2{
```

Y está es una contraseña con la misma configuración que use para la que sí me
funciono, sin caracteres especiales:

```
GVNfEB7ApUs3C8DAyPnq
```

**Comment by aniolm9** [comment]
I have just tested with the passwords you provided and I'm having the issue too. I'll create an internal ticket to solve it. I have also noticed that the cloud isn't working without a "Display Name", so I will open a ticket for that too.
